### ISSUE TITLE
Parser meta-issue

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1031]
This issue attempts to collect the parser bugs we'll need to fix to meet user expectation:

- [x] `where {$it.size > 10kb}` doesn't work: https://github.com/nushell/book/issues/37
- [ ]  boolean values can't be parsed: https://github.com/nushell/nushell/issues/98
- [ ] && not supported, but also doesn't error - https://github.com/nushell/nushell/issues/293
- [x] bare tokens should support `+` - https://github.com/nushell/nushell/issues/434
- [x] bare tokens should support `-` - https://github.com/nushell/nushell/issues/719
- [x] bare tokens rejecting either `@` or `:` - https://github.com/nushell/nushell/issues/922
- [ ] bare tokens should support `[` and `]` - https://github.com/nushell/nushell/issues/933
- [x] flags are forced to be at the end - https://github.com/nushell/nushell/issues/865
- [ ] mistyped operator needs better error - https://github.com/nushell/nushell/issues/709
