### ISSUE TITLE
Inconsistent naming of types and their associated commands and `SyntaxShape`s

### ISSUE THREAD

**Issue by sholderbach** [nushell/nushell#10332]
We have a few "types" where the naming is not perfectly consistent across the user facing interface:
- The commands specific to the type (e.g. `date now`)
- The `Type` name accessible through `describe` (e.g. `1.0 | describe` `float`)
- The `SyntaxShape` i.e. the thing you can cue the parser to which is the thing the type annotations in `def`s are turned into (e.g. `def foo [bar: datetime]`)
- Documentation inside and outside the application when referring to that.

On top of that our internal symbols should follow the same names for better discoverability.

## `decimal` -> `float`

Here the direction to move is obvious as `float` is more true to what the capabilities of the underlying data type is (not money-safe, fast for approximate math)

Status copied from https://github.com/nushell/nushell/pull/10320#issuecomment-1714553554
- [x] `into decimal` deprecated in favor of `into float` #9979 
- [x] `random decimal` deprecated in favor of `random float` #10320 
- [x] `describe`/`Type::to_string()` is `float`
- [ ] Parser accepts both `decimal` and `float`...
- [ ] to define `SyntaxShape::Decimal`
- [x] `StyleComputer` to map in the config uses the type name so `float` 

## `date` vs `datetime`

This is more contentious: `date` has a nice brevity for the command names but the capabilities for time are expressed by `datetime`

- [ ] `date ...` family of commands (effectively the methods/class functions :P)
- [ ] `format date` as the corresponding format command
- [ ] `into datetime` as the cast
- [ ] `seq date` for sequence generation
- [ ] `Type::Date`
- [ ] `date now | describe` returns `date` (#10298)
- [ ] `SyntaxShape::DateTime`
- [ ] For command arguments `: datetime`
- [ ] (Dataframes make a distinction between the two types: `dfr as-date` and `dfr as-datetime`)

## Addendum `Path`
To the user the distinction between `Type` and `SyntaxShape` is probably not strictly obvious. We should also try to get them as close as possible. Here a notable outlier is for example `:path` is `SyntaxShape::Path` that enables important completions but doesn't exist inside the `Type`/`Value` system

**Comment by 1Kinoti** [comment]
`int` vs `integer`

[`Type::Int`](https://github.com/nushell/nushell/blob/8f4ea69c22dc9d2d1b86499330f095a76c8c569d/crates/nu-protocol/src/ty.rs#L24)
[`SyntaxShape::Int`](https://github.com/nushell/nushell/blob/8f4ea69c22dc9d2d1b86499330f095a76c8c569d/crates/nu-protocol/src/syntax_shape.rs#L62)
[`random integer`](https://github.com/nushell/nushell/blob/8f4ea69c22dc9d2d1b86499330f095a76c8c569d/crates/nu-command/src/random/integer.rs#L15) <~ culprit
[`into int`](https://github.com/nushell/nushell/blob/8f4ea69c22dc9d2d1b86499330f095a76c8c569d/crates/nu-command/src/conversions/into/int.rs#L27)
