### ISSUE TITLE
Reddit-reported user experience report issues

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1130]
Issues from a recent user experience report: https://www.reddit.com/r/programming/comments/eei1qg/nushell_a_modern_shell_for_the_github_era/fbuusz1/

- [x] Book needs to be updated to latest (hit https://github.com/nushell/nushell/issues/1099 and possibly others)
- [ ] Book needs better follow (user confused we never say how to set variables. PLS that we can't use variables yet)
- [x] `where { $it.size > 10kb }` canonical form doesn't work anymore
- [ ]  Unexpected arguments to most built in commands do absolutely nothing. I expect failure on unexpected arguments
- [x] The book also talks about a fetch command to fetch urls, but it doesn't exist in my installation of the latest version (make sure 'stable' set is always availble)
- [ ]  I quickly found situations where I don't know how to operate and I can't find the information in the book or otherwise, like this:
```
/home/taylor/Projects/work/myjavaproject(edge)> open pom.xml | get project.properties
━━━━━━━━━━━━━━━━
 <value> 
────────────────
 [table 5 rows] 
━━━━━━━━━━━━━━━━
```
 - [ ] enter is also apparently buggy for many datatypes:
```
/home/taylor/Projects/work/myjavaproject(edge)> enter pom.xml
/(edge)> ls
━━━━━━━━━━━━━━━━━
 project 
─────────────────
 [table 12 rows] 
━━━━━━━━━━━━━━━━━
/(edge)> cd project
/project(edge)> ls
━━━━┯━━━━━━━━━━┯━━━━━━━━━━┯━━━━━━━━━━┯━━━━━━━━━━┯━━━━━━━━━━┯━━━━━━━━━━┯━━━━━━━━━━┯━━━━━━━━━━┯━━━━━━━━━━┯━━━━━━━━━━┯━━━━━━━━━━┯━━━━━━━━━━
 #  │ modelVer │ version  │ groupId  │ artifact │ packagin │ properti │ name     │ descript │ reposito │ <value>  │ dependen │ build 
    │ sion     │          │          │ Id       │ g        │ es       │          │ ion      │ ries     │          │ cies     │  
────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────
  0 │ [table 1 │          │          │          │          │          │          │          │          │          │          │  
    │ rows]    │          │          │          │          │          │          │          │          │          │          │  
  1 │          │ [table 1 │          │          │          │          │          │          │          │          │          │  
    │          │ rows]    │          │          │          │          │          │          │          │          │    
...
━━━━┷━━━━━━━━━━┷━━━━━━━━━━┷━━━━━━━━━━┷━━━━━━━━━━┷━━━━━━━━━━┷━━━━━━━━━━┷━━━━━━━━━━┷━━━━━━━━━━┷━━━━━━━━━━┷━━━━━━━━━━┷━━━━━━━━━━┷━━━━━━━━━━
/project(edge)> cd properties
error: Can not change to path inside
- shell:1:13
1 | cd properties
  |    ^^^^^^^^^^ No such path exists
```

**Comment by thegedge** [comment]
@jonathandturner do you think there's still something actionable here?

**Comment by pwnorbitals** [comment]
how up-to-date is this issue ?

**Comment by jonathandturner** [comment]
@pwnorbitals - looking through it, it's hard to see what still needs fixing and what needs documentation.

I think the unexpected arguments may still have cases that need fixing. Would be with exploring if someone wanted to see what we don't warn on.
