### ISSUE TITLE
add uutils/coreutils commands into nushell

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#11549]
### Related problem

This is a tracking issue to add the agreed to uutils/coreutils commands to nushell

- [ ] cat
- [ ] cp [pr](https://github.com/nushell/nushell/pull/10097)
- [ ] df
- [ ] du
- [ ] hostname
- [ ] kill
- [ ] ln
- [ ] ls
- [ ] mkdir [issue](https://github.com/nushell/nushell/issues/10515) [pr](https://github.com/nushell/nushell/pull/10785)
- [ ] mktemp [issue](https://github.com/nushell/nushell/issues/10845) [pr](https://github.com/nushell/nushell/pull/11005)
- [ ] mv [issue](https://github.com/nushell/nushell/issues/10446) [pr](https://github.com/nushell/nushell/pull/10822)
- [ ] rm [issue](https://github.com/nushell/nushell/issues/10447)
- [ ] touch
- [ ] uname
- [ ] who
- [ ] whoami [pr](https://github.com/nushell/nushell/pull/10488)

### Describe the solution you'd like

We'd like to implement all these commands using uutils/coreutils. Some work may have to be done on the uutils/coreutils side. All the commands so far have had to have options exposed.

If you'd like to sign up for one of these commands, feel free to post below and we can put your name by the command.

**Comment by dmatos2012** [comment]
I could volunteer for `uname` seems very straightforward tho. Initially, we would have to see again how many flags we are going to support, but we can give it the initial roll out :)

**Comment by fdncred** [comment]
Sounds good @dmatos2012. I'll put your name by it. Hopefully a very different experience from uu_cp and uu_mv. 😆

**Comment by ysthakur** [comment]
I can try to work on `touch`

**Comment by fdncred** [comment]
Thanks @ysthakur I added you above.

**Comment by jokeyrhyme** [comment]
In terms of general direction/expectations, if a coreutils implementation doesn't work on Windows, is it acceptable to replace the UNIX/Linux/macOS behaviour with coreutils and leave the pre-coreutils implementation alone for Windows?

Or do we need to try to get upstream coreutils to work on Windows first?

**Comment by fdncred** [comment]
We want to use the cross-platform coreutils. We do not want to have a separate implementation for Windows and Unix.

**Comment by dmatos2012** [comment]
@fdncred). I was curious about `du` but I see that we already have pretty tables and all as output, so are we still planning on replacing it?

Additionally, all the other commands have a huge number of flags, shall we consider how many are we going to support for some of them?  I can envision maybe `df` being `nushell-like` with almost no flags, but the others seem that they are too unstructured. Thoughts? 

A

**Comment by fdncred** [comment]
@dmatos2012 The general idea is to migrate all the commands listed. As far as flags, we just need to add the most popular ones as a first pass, or the ones that already exist in the nushell built-in command. If people want other flags, we may add them via separate PR. I'm fine with discussing flags in a per command PR basis.

Keep in mind, that one of the reasons why we chose to add coreutils utilities is because it lowers the maintenance costs for us once it's in, or at least that's the idea. We have all these excellent tools that they created, and we'd like to use them. I agree that 100 flags is not the nushell way, but we should just start somewhere and go from there.

**Comment by philocalyst** [comment]
I'd volunteer for ls! @fdncred

**Comment by fdncred** [comment]
@philocalyst I've tried but the uutils folks aren't super responsive anymore https://github.com/uutils/coreutils/pull/9851

**Comment by amandalewis1231-lgtm** [comment]
Thanks for the update regarding the responsiveness of the uutils team.
Since things seem to have stalled with their repository, how would you like
us to proceed with the ls implementation?

**Comment by sylvestre** [comment]
Uutils here. Still interested in helping. It is just that we have a lot of pr and it is too easy to miss one. Sorry

**Comment by fdncred** [comment]
Thanks @sylvestre. Appreciate the response. We totally get it. I rebased the PR. It was a total mess after bit-rotting for so long. Hope I didn't miss anything.

**Comment by philocalyst** [comment]
I'd take on `df`? Congrats on your merge for `ls` btw @fdncred !

**Comment by fdncred** [comment]
As long as it's cross platform it would probably be ok.

**Comment by sylvestre** [comment]
df is cross platform too

**Comment by philocalyst** [comment]
unfortunate news is that df isn't really exposed as a library-like interface, similar to the original `ls` -- but you guys would accept a PR I hope? @sylvestre ?

**Comment by sylvestre** [comment]
sure, as long as the PR is reasonable

**Comment by philocalyst** [comment]
Got [this up](https://github.com/uutils/coreutils/pull/12281) any folks who have time would love feedback!

**Comment by oech3** [comment]
Why do not just call `uu_app`?

**Comment by fdncred** [comment]
@oech3 I just answered this question in the uutils repo. Feel free to investigate our source code and look at the other uutils crates we've implemented. All of them had to have changes in the uutils repo in order to integrate properly with nushell. Also, why is your profile private? It's giving me AI-bot vibes.

**Comment by oech3** [comment]
OK.

I'm not a bot. Just nothing to write to profile.

**Comment by fdncred** [comment]
Just what a bot would say. 😆

**Comment by oech3** [comment]
I would just generate profile if I am bot.
