### ISSUE TITLE
Use Span IDs instead of Spans

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#12963]
### Related problem

To prepare ground for the new parser, we need to be able to refer to spans by their IDs. This is a big undertaking that can be separated into multiple steps to help spread the work over multiple PRs:

- [ ] [Step 1](https://github.com/nushell/nushell/pull/12960): (this PR) Adds a `SpanId` type and a corresponding `span_id` field to `Expression`. Parser which creates expressions will now add them to an array in `StateWorkingSet`, generates a corresponding ID and saves the ID to the Expression.
- [ ] Step 2: Instead of Expression's `span`, use `span_id` and look up the span from `EngineState`/`StateWorkingSet` (plus relevant helpers to do that). This can be done gradually case by case even in several PRs, always making sure that all tests pass.
- [ ] Step 3: Add a new `ActualSpan` struct which is identical to `Span`. Use that in the parser and similar places where new spans and their IDs are created. Next,  rename `Span` to `SpanWithId`  and add new `id: SpanId` field. This struct is now used everywhere where we'll eventually want to use `SpanId`. Rename `ActualSpan` to `Span` to keep the naming less arcane.
- [ ] Step 4: Refactor all usages of `SpanWithId` to use only the `id` field and not use `start`/`end`. Can be done gradually over multiple PRs. Might require adding a few helpers here and there and refactoring/removing stuff like `Span::concat()` etc.
- [ ] Step X: At some point `flatten_xxx()` functions needs to be refactored to take `&mut StateWorkingSet` and act as another parser stage because flattening adds new spans and we need IDs for them. This is necessary for `SpanId` integration to syntax highlighting, completions etc. which depend on flattening.
- [ ] Step Y: Hack miette at some point to work with `SpanIds` because `ShellError`s will have `SpanWithId` instead of `Span`. This could eventually handled upstream making a PR to miette to support a custom span translator.
- [ ] Step 5: Remove `start` and `end` fields from `SpanWithId`. Big milestone.
- [ ] Step 6: `SpanWithId` now contains only the `id` field. Transfer all its remaining methods to the `SpanId` and remove `SpanWithId` altogether. Now, we use `SpanId` everywhere, congrats!

When actually using the new parser, SpanIds will become NodeIds.

### Describe the solution you'd like

`Span`s will only be used by the parser and a handful of places where manual span creation is allowed to happen (like flattenning or tests). All other places will refer to these pre-created spans by their IDs.

**Comment by fdncred** [comment]
as requested @cassaundra, we're tagging you here as something to jump in on that will lead us to the new nu parser. also there's now a #new-nu-parser channel on discord in case you haven't seen it.

**Comment by cassaundra** [comment]
Happy to help if needed! It looks like a good amount of progress has been made so far--@WindSoilder, are you planning on doing the second half you mentioned in your commit, or is that more to lay the groundwork?

**Comment by WindSoilder** [comment]
@cassaundra Sorry, I don't have too much time to look into this yet.  Feel free to do it
