### ISSUE TITLE
Steps for adding aliases

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1343]
Part 1: Get blocks working
- [x] Get blocks working again (syntax)
- [x] Get canonical `where` working again
- [x] Add test assets for working blocks

Part 2: Pipeline blocks
- [x] Change blocks to hold pipelines (syntax)
- [x] Refactor pipeline processing so that it returns a stream of values
- [x] Extend evaluator to handle evaluating blocks
- [x] Allow commands to evaluate and drain results into a collection of values
- [x] Add test assets for pipeline blocks and draining results

Part 3: Aliases
- [x] Add `alias` command that returns an AddAlias action
- [x] Add test assets for `alias`

Part 4: Block parameters
- [ ] Extend blocks to allow for parameters
- [x] Extend evaluator to bind to block parameters
- [x] Error when evaluating and block parameters are unbound
- [x] Ensure that parameters works with `alias`
- [ ] Add test assets for block parameters and error cases

**Comment by wycats** [comment]
I'm gonna start this off by making the block parser and the any expression parser handle braced blocks. I'm not entirely sure when that stopped working, but it shouldn't be too hard to fix.
