### ISSUE TITLE
Cal command future todos

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#1740]
Here are some notes I made for myself while create the `cal` command.  I'm making an issue just to keep them with the project.  Any of these that are not wanted by the maintainers can be removed.

- [ ] Find a good way to display the current day.  Much discussion went on about how do this properly in a way that keeps the values in the table as integers and without adding additional columns that would just repeat the current day for each row (which ends up looking weird).  In `add_month_to_table()`, there is an input parameter called `_current_day_option`, which currently isn't being used (hence the underscore), but this can be used in the future when how it will be used is decided.  This is a `Option<u32>` because the table is built by months and only one month has a current day, the rest do not.

- Once https://github.com/nushell/nushell/issues/1737 is resolved:
    - [ ] Verify that `cal` can accept negative years.  
    - [ ] Verify that very large negative numbers for years (values that should break Chrono) report an error to Nushell (this is how very large positive numbers that break Chrono work).

- Flags to consider/implement:
    - [ ] “week” to add a week number column
    - [ ] A "this-week" or "today" flag to show only the row for the current week
    - [ ] [Other `cal` flags](http://man7.org/linux/man-pages/man1/cal.1.html)?

- Clippy:
    - [X] Remove the #[allow(clippy::too_many_arguments)] attribute and actually deal with the issue: https://github.com/nushell/nushell/commit/40ec8c41a02c68d8a0b14c5877e206fa09ceda87
        - possibly grouping some items together in a struct, like the year, month, date items.

- Cleanup:
    - Code deletion:
        - [X] Can month name be determined by Chrono? https://github.com/nushell/nushell/pull/1990
        - [ ] Can list of day names be generated by Chrono?
    - Miscellaneous:
        - [X] There may be a way to declare certain variables with different data types that will reduce the number of `as` typecasts: https://github.com/nushell/nushell/pull/1886
        - [X] Don't display the year and month be displayed by default https://github.com/nushell/nushell/commit/f702aae72fd4d218ead1bd639d99b999198fef3b

- [ ] Do any other tests need added?
- [x] Update Nushell website with `cal` command doc

**Comment by jonathandturner** [comment]
Was playing with this, it's a lot of fun :)

Something I was wondering - should the `year` and `month` be displayed by default?  The user could optionally add them, but I noticed on 80x24 terminals that the columns get cut off.  Just thought I'd mention it while you're looking into improvements.

**Comment by JosephTLyons** [comment]
I can see being able to add in the year and month optionally as an improvement since you can customize it how you want.  A few questions.

1) The current `--year` flag name might need to change, since I feel like `--year` and `--month` would be the names of the flags that add those columns in.  Then there would be a new name for specifying showing the full year.

2) Would the full year flag automatically show the year and month, or would it act just the same as the single month view, where you would still specify month and year individually?
