### ISSUE TITLE
Improve architecture of nu-cli

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#1896]
`nu-cli` has a lot of coupling, which makes it hard to make certain kinds of changes without changing large portions of the codebase. I'd like to investigate the existing structure and find ways to improve our architecture.

- [ ] Graph existing coupling between structures / modules.

<details>
<summary><b>Previous description</b></summary>
`nu-cli` is quite a large crate. I envision it to be light on the code side, mostly just gluing together other crates into the CLI that we all love today.

Here are the concepts in `nu-cli` today:

- Streams
- Evaluation
- Commands
    - Abstractions
    - Concrete implementations (e.g., `du`, `ls`, and so on)
- Engine (pipeline execution, internal/external command execution, etc)
- Shells
    - Completions
- Highlighting / painting
- Data fetching (e.g., config)
- Other utils
- Environment

My first attempt at pulling these out into separate subcrates proved unwieldy, so I'm going to break this up into smaller steps. The crates that I was trying to migrate to:

- [x] Streams
- [ ] Shells
- [ ] Commands (the base/abstractions, not the concrete implementations)
- [ ] Command implementations
- [ ] Engine (evaluation and execution)
- [x] Completions
</details>

**Comment by thegedge** [comment]
I've tossed around this decomposition in my head, and instead of worrying about whether or not it's perfect, I figure it's best to have some kind of decomposition. It'll be easy to merge crates into others if we think they're too small or it's a pain to maintain so many.

**Comment by thegedge** [comment]
Just learned from @jonathandturner that we're publishing all of our subcrates. Given that, I think the crates themselves should be useful on their own, and I don't think the decomposition I gave above achieves that.

I'll instead switch this issue to better decoupling our existing modules in `nu-cli` so that a future crate refactor will be far simpler.

**Comment by jonathandturner** [comment]
We've split the old nu-cli into several crates that specialise in different areas, including engine, commands, and more. I think we can mark this as done.

We can do additional documentation in general inside the source code, in the source tree, and also on the documentation repo. I think what I'll do is collapse the "the source needs more docs" into a single meta-issue that talks about the places that still needs docs.
