### ISSUE TITLE
After improved Value spans todo list

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#193]
After spans are added to Values which contain the location those Values come from, there are a lot of additional steps we can take to make things generally work better:

- [x] Let save be called without arguments, so that it uses the filename given via the span
- [x] View structured text contents by looking at the filename to detect markdown, source files, etc
- [ ] Use file extensions to improve binary data type detection
- [x] .sav file support

**Comment by jonathandturner** [comment]
Closing this for now, but we can still use the metadata for better filetype detection
