### ISSUE TITLE
Ensure that all commands stream their results

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#2110]
**Is your feature request related to a problem? Please describe.**
A few commands do not stream their results, while a majority of them do.  There may be others, but these ones for sure do not:

- [ ] `cal`
- [X] `drop`* https://github.com/nushell/nushell/pull/2114
- [X] `every` https://github.com/nushell/nushell/pull/2118, https://github.com/nushell/nushell/pull/2120
- [X] `from_vcf` https://github.com/nushell/nushell/pull/2137
- [X] `last`* https://github.com/nushell/nushell/pull/2143
- [ ] `sort-by`
- [ ] `unique`

`*` = these cannot cannot be truly streamed, as we need to know the number of rows the table has for the current calculation, but some small improvements have been made to them

Some, if not all of these, no longer stream after I moved them off of `async_stream` using this method, which probably shouldn't of happened.

Some additional updates to streaming (as mentioned by @jonathandturner) will occur here:

- [ ] `fetch`
- [ ] `lines`
- [ ] `post`

The repo should probably be checked to see if there exists any others that do not stream their results.

**Describe the solution you'd like**
Instead of filling up a vec of items to return, convert the functions to stream their results

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jonathandturner** [comment]
Some I'd like to make more stream-y:

- [ ] fetch
- [ ] post
- [ ] lines

**Comment by arashout** [comment]
I can look into `fetch` since I did open

**Comment by arashout** [comment]
I'm going to try my hand at `fetch`

**Comment by JosephTLyons** [comment]
I have  `every`, `from_vcf`, and `last`, aside from one error on each of them (the same error) that I can't get around current.

**Comment by JosephTLyons** [comment]
The `cal` one will be horrendous.  That was the first major thing I added to nushell and I passed a vec around to a bunch of functions and added the rows to it, so I have no idea how that will be converted.
