### ISSUE TITLE
MVP #2 - 'chsh' and command cleanup

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#261]
"chsh" and standardize commands

This is the plan for the 2nd MVP. See #122 for the 1st planned MVP.

# Essentials
- [x] should be able to `chsh` (related to #80)
- [ ] Commands/plugins calling each other (https://github.com/nushell/nushell/issues/180)
- [x] command argument shortforms
- [x] help
- [ ] `less` functionality for printing large tables or trees
- [x] Environment variable support (needs mini-design)
- [x] && separator (implemented as `;`)
- [x] non-X11 Linux mode (#322)
- [x] Stability fixes/catch panics (#294)
- [x] Survey all unwraps. (#300)
- [x] Return errors instead of panicking
- [ ] catch all panics

# Nice-to-haves
- [x] paths from $it (eg `$it.authors`)
  - [x] for internal commands
  - [x] for external commands
- [x] better match command (eg `match "{first name} {last name}"`)
- [x] Some sort of video

**Comment by ijt** [comment]
chsh already works for me with `nu` on Linux:

<img width="975" alt="Screen Shot 2019-08-24 at 6 20 25 PM" src="https://user-images.githubusercontent.com/15530/63644361-71ebfe00-c69c-11e9-84e8-6b25d05e7cc6.png">

and on Mac (had to edit /etc/shells first). Is there something more to it than that?

**Comment by jonathandturner** [comment]
@ijt the basic stuff works though you might run into problems when you try to access commands in your path or work with environment variables

**Comment by ijt** [comment]
Got it. I think it could help to see some examples of what currently
doesn't work.

**Comment by jonathandturner** [comment]
@ijt - I just tried `chsh` for Nu on my Pop! OS Linux box, and it seems to mostly "just work". It appears to do this by spawning a `sh` to start Nu from, which gives access to the path and environment variables. This may mean that some distros can run in this mode while others may need more complete support.

**Comment by ijt** [comment]
Got it. Makes sense.

**Comment by stephanemagnenat** [comment]
What about making errors non-crashing (see issue #294)? For the new-coming users, it is frustrating that the shell, which looks very friendly and easy to get to use, crashes when provided with invalid arguments (see issue #599), which somehow defeats discoverability.

Of course, for power users this is not a problem, so I can also understand it is not a top priority, but nonetheless I believe nu has a huge potential and that potential would be nicely served by making it very easy to approach and discover.

**Comment by jzaefferer** [comment]
> less functionality for printing large tables or trees

I think #999 could be added there. Maybe related is #389

> && separator

Isn't this now implemented as `;`, like `make; ./run/my/app`?

> Stability fixes/catch panics (#294)

The ticket is closed, so is this done?

All in all: Maybe the leftovers can be moved into another milestone and this considered done.

**Comment by thegedge** [comment]
> All in all: Maybe the leftovers can be moved into another milestone and this considered done.

I think so too, but I'll defer that decision to @jonathandturner 🙂
