### ISSUE TITLE
The big todo list

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2858]
I've noticed I keep making mental notes about things that need to happen, so before I forget I want to put them into some place (we can make separate issues for these if we want, it's just easier to type thing into one issue to start).

- [ ] we need to add a config handler (which has largely already been implemented, it's just waiting to be fully wired up) to the global context so that we don't load from the file each time we read a config setting.
- [ ] connect to above: we can make a `config reload` to manually kick off a reload
- [ ] I managed to make `source` require a filepath constant, which opens the door up to even better import functionality. At that point, `source` would basically be like an `import *` into the current scope.
- [ ] we need to add to extend the parser to also return all files it loaded, so that we can error properly in code loaded from other files
- [ ] connect to above: we need to use this file cache when we run the `source` command, so that we don't load/parse the contents twice
- [x] we don't yet support marking parameters as optional/required in custom commands
- [x] we don't support shorthand flags in custom commands (or adding a shorthand to a longhand flag)
- [x] we don't support rest params in custom commands
- [x] we don't support adding descriptions to custom commands
- [x] maybe: would it be interesting to add the ability to query the context for what commands, variables, and aliases are in scope?
- [x] You can assign blocks to variables `let foo = { ... }`, and then run them using the variable as the command name `$foo` but you can't yet specify parameters to the block

**Comment by stormasm** [comment]
>> would it be interesting to add the ability to query the context for what commands, 
>> variables, and aliases are in scope?

Yes, I think this is a great idea !
I will start taking a look at what it would take to do this...

**Comment by fdncred** [comment]
Documenting for posterity here as a +1 to optional parameters. Zoxide, [as described here](https://github.com/ajeetdsouza/zoxide/issues/69#issuecomment-754108982), needs that functionality. I see it's on the list but when it's ready I have a real-world scenario that I can test with.

**Comment by fdncred** [comment]
@stormasm I wonder what the "right" way to do that is. Perhaps something similar to `$nu.variable` such as `$scope.variable`? so you could do `echo $scope` or `echo $scope.variable` the same way that right now we can do `echo $nu` or `echo $nu.variable`.

**Comment by LhKipp** [comment]
@jonathandturner Regarding the tasks involving the def command. Do you already have specific syntax in mind for optional / mandatory flags / parameters, rest arguments, ... ?

**Comment by treybrisbane** [comment]
>You can assign blocks to variables `let foo = { ... }`, and then run them using the variable as the command name `$foo` but you can't yet specify parameters to the block

@jonathandturner Sounds like you're considering having multiple ways of defining functions. Is that correct?

I realise the syntax for defining functions has already shipped, so it's probably too late for this kind of question, but... Have you considered simply using function expression assignments as _the_ means of defining functions?

E.g.
```
let add = [x, y] {
    = $x + $y
}
```
instead of
```
def add [x, y] {
    = $x + $y
}
```
???

Using that syntax would _I think_ give you a single uniform way of defining functions. Not entirely sure what the limitations may be though.

Apologies if this has already come up. I'm just passively lurking the repo at this point! 😀

**Comment by jonathandturner** [comment]
@treybrisbane I'm always up for ideas :) For your idea - the difference here is the order of definition. With `def` we can make sure all functions are defined before expressions run. If we make it on the level of expressions, we can't make that guarantee, as expressions need to evaluate one after another.

We'd probably also need to do steps like Ocaml did with `let rec` so the function could see itself.

**Comment by jonathandturner** [comment]
@LhKipp - I don't have any specific syntax in mind, yet. I think "something reasonable" so that it's not surprising to people. :)

**Comment by treybrisbane** [comment]
> With `def` we can make sure all functions are defined before expressions run.

Ahh, okay. I didn't realise that was a design goal. My bad!

Although that definitely makes the `let foo = { ... }` case more interesting, as it's kinda defining a pseudo-function-ish thing that I'm guessing isn't subject to this restriction?
