### ISSUE TITLE
Target stable Rust

### ISSUE THREAD

**Issue by est31** [nushell/nushell#362]
Right now nushell seems to require Rust nightly. But this hampers adoption, for example linux distros can't include it this way. It would be great if eventually, nushell would work on Rust stable.

futures-async-stream unrelated nightly features:

- [x] #367
- [x] type_name #371
- [x] option_flattening #468
- [x] try_trait #520
- [x] crate_visibility_modifier #526 , https://github.com/Hoverbear/getset/pull/28 , #561
- [x] bind_by_move_pattern_guards #521 
- [x] specialization #531, #569 , #579
- [x] in_band_lifetimes #527
- [x] https://github.com/wycats/language-reporting https://github.com/wycats/language-reporting/pull/7

futures-async-stream related nightly features:

- [ ] proc_macro_hygiene https://github.com/nushell/nushell/pull/724
- [ ] generators https://github.com/nushell/nushell/pull/724
- [ ] https://github.com/taiki-e/futures-async-stream https://github.com/nushell/nushell/pull/724

**Comment by jonathandturner** [comment]
Yeah, we'd love to be on stable eventually. We'll have to wait for async/await, async streams, and potentially also more, but we'd definitely love to see all of that in stable.

**Comment by est31** [comment]
The async/await MVP is stable already (on the nightly channel atm but will arrive in 1.39 unless it's backed out). I did see some futures/async related feature gates though when I compiled on stable:

```
error[E0554]: #![feature] may not be used on the stable release channel
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.1.0-alpha.2/src/lib.rs:179:1
    |
179 | #![feature(gen_future, generator_trait, generators)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by zimbatm** [comment]
Just my two cents; today I started packaging nushell for [nixpkgs](https://github.com/NixOS/nixpkgs) and got stuck on the async build error.

**Comment by jonathandturner** [comment]
Working on bind_by_move_pattern_guards

**Comment by taiki-e** [comment]
> futures-async-stream related nightly features: Upstream dependencies needing nightly:
> 

futures-async-stream aims to provide higher performance by using unstable features (in particular, it is expected to function in the same way as future language features).
If you want to work with the stable version, consider using https://github.com/tokio-rs/async-stream. I think there are some limitations, but it should probably work. (disclaiminer: I'm involved in the maintenance of both crate.)

**Comment by taiki-e** [comment]
> * [ ]  in_band_lifetimes

(btw, in_band_lifetimes should be unrelated to futures-async-stream.)

**Comment by taiki-e** [comment]
I'm working on in_band_lifetimes.

**Comment by taiki-e** [comment]
Seems [`ExtractType` trait](https://github.com/nushell/nushell/blob/1d64d90419d0523fe035ebce4f8f0f01cd838b6a/src/object/types.rs#L6) (the only user of specialization feature) is not actually exported to the public, but to remove the usage of specialization feature, it seems necessary to check that `V::Value` implements `ExtractType` trait ([seems it is not yet supported?](https://www.reddit.com/r/rust/comments/29hvwg/runtime_trait_implementation_checking/)).
https://github.com/nushell/nushell/blob/1d64d90419d0523fe035ebce4f8f0f01cd838b6a/src/parser/deserializer.rs#L76

**Comment by est31** [comment]
I think I have a way to get rid of specialization. I'm working on a PR now.

**Comment by est31** [comment]
Hmmm nevermind. I think there is no way to get rid of specialization without also not using serde for deserializing the cli arguments of the commands. Which is a larger project as it involves having to write a proc macro (or find a preexisting one that does it). I've thought I could use the Any trait but deserialize_any doesn't even require that one. I've filed a PR for the lower hanging fruit that likely @taiki-e also found: #531

**Comment by taiki-e** [comment]
If I understand correctly, the current status is as follows:

* specialization: cannot be replaced with a stable one yet (https://github.com/nushell/nushell/issues/362#issuecomment-526229061).

* replaceable features 
  * in_band_lifetimes (#527): this is probably useful (https://github.com/nushell/nushell/pull/527#issuecomment-526237799)
  * futures-async-stream related nightly features (https://github.com/nushell/nushell/issues/362#issuecomment-526147894): this is probably more efficient than the alternative (generators are really lazy).

  so keep it as long as we need it nightly is preferable?

* (the usage of other unstable features has been removed.)

**Comment by wycats** [comment]
@est31 @taiki-e I just want to say that you folks are amazing. Thank you!

**Comment by wycats** [comment]
@taiki-e I've always expected specialization to be "the hard one", because it was the only (straight-forward?) way I could figure out to support deserialization of arguments, and the benefits of that approach are very significant.

Annoyingly, the blanket impl just panics, so it's not even a very interesting use-case for specialization.

**Comment by nikomatsakis** [comment]
@jonathandturner 

> Working on bind_by_move_pattern_guards

fyi that is nearing stable, see https://github.com/rust-lang/rust/pull/63118

**Comment by est31** [comment]
In PR #579, I remove the last use of specialization. Now, only the async related features remain. As I'm not very familiar with the async ecosystem, I leave this to others. We're almost there!

For constraints, nushell uses the `async_await` syntax. Thus the earliest stable release it may run on will be 1.39, released November 7th, 2019. So there's time to get rid of the unstable async related features until that date.

**Comment by jonathandturner** [comment]
I just saw in https://github.com/taiki-e/futures-async-stream#how-to-write-the-equivalent-code-without-this-api that they explain how to rewrite the code to not use the macro (and seemingly also the generators unstable feature)

I haven't had a chance to investigate further yet, but wanted to post it here in case someone else wanted to.

**Comment by est31** [comment]
Alright, as nobody else seems to have stepped up, I've implemented @taiki-e 's suggestion from https://github.com/nushell/nushell/issues/362#issuecomment-526147894 in PR #713 (at least the lower hanging fruit).

**Comment by est31** [comment]
Nushell now compiles on beta and once Rust 1.39.0 is released, it will compile on stable as well. Thanks everyone who helped with this! @djc @taiki-e @jonathandturner
