### ISSUE TITLE
0.60 release checklist

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#4356]
(warning: this list may not be complete, and may have items added as we discover them):

## Commands

- [x] post - [efx]
- [ ] benchmark (remaining: passthrough param)
- [x] match (regex type) (Jakub: I'd suggest folding it into `find`)
- [x] roll (roll, roll column, roll up)
- [x] headers
- [x] format filesize
- [ ] chart (chart, chart bar, chart line)
- [x] histogram
- [x] reduce (parser support for `$acc` and `$it` instead of putting both inside `$it`)
- [x] `save --append`
- [ ] group-by date (jt: this should probably be `group-by --date` since `group-by date` is ambiguous with a "date" as a column name')
- [x] ~into cell-path? (jt: is there a use case for this one? I think since e-q allows strings as cell-paths you might not need it?)~
- [ ] plug-ins: to bson, from bson
- [ ] plug-ins: to sqlite, from sqlite
- [ ] plug-ins: s3 
- [x] plug-ins: binaryview (no need to port)
- [ ] plug-ins: start
- [ ] plug-ins: inc (still needs some work)

## Features

- [x] finish custom external completions, `git` as main use case for initial design
- [x] generate a config.nu if it's not there nushell/nushell#4348
- [x] lib_dirs (path for scripts, so `use` will look in these dirs)
- [x] LAST_EXIT_CODE to get the exit code of the last command (internal or external)
- [x] Update https://www.nushell.sh/book/command_reference.html
- [x] Automatic parsing of env vars (like PATH/Path) based on OS without needing config.nu
- [ ] Cell-path completions https://github.com/nushell/nushell/issues/4372
- [x] Use kebab-case instead of snake_case for config points (jt: if column names are snake_case, then the config points would also be snake_case)
- [x] Use kebab-case instead of snake_case for cell paths (e.g., `help commands`) (jt: I think we ended up thinking column names should be snake_case. with that being true, cell paths would also be snake_case)
- [x] Update README

## Missing config points - to add or not to add?
- [ ] complete_from_path: bool
- [ ] ctrlc_exit: bool
- [x] disable_table_indexes: bool
- [ ] nonzero_exit_errors: bool
- [x] ~skip_welcome_message: bool (jt: we no longer show a welcome message, so this probably isn't needed?)~
- [x] ~pivot_mode: auto, always, never (jt: because of records, some cases we needed this aren't needed anymore. I don't think we need this?)~

## 3rd Party Integrations

We should ensure these are working or pr changes to their repo.

- [x] [zoxide](https://github.com/ajeetdsouza/zoxide)
- [x] [starship](https://starship.rs) - works
- [ ] [starship script to PR](https://github.com/starship/starship/blob/master/src/init/starship.nu)
- [ ] [starship docs to PR](https://github.com/starship/starship/tree/master/docs#nushell)
- [x] python virtualenv
- [x] couchbase
- [x] [oh-my-posh](https://ohmyposh.dev/docs/windows) - works
- [ ] [oh-my-posh docs to PR](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/docs/docs/install-shells.mdx#nu--0320)

## Document as "needs design" post-merge

- [ ] Autoenv
- [x] history file vs. multiple sessions? should be taken care of by https://github.com/nushell/reedline/pull/299

## CI / Repo Root folders

- [x] release ci - do we need any changes? wix, etc
- [ ] winget ci
- [x] stale ci - keep or chunk?
- [ ] wasm (won't block release if we don't get to it)

## Bugs

- [ ] `use` + path autocomplete: nushell/nushell#4352
- [x] Aliases crashing https://github.com/nushell/nushell/issues/4303

## Checks 

- [ ] make sure LS_COLORS is retained when passing `ls` through all the filters commands (see https://github.com/nushell/engine-q/pull/824) (fixed sort-by, find, merge, others?)
- [x] nushell/nushell#4309 - closed by #4525
- [x] nushell/nushell#4306 - closed by #4525
- [x] last - closed by #4525
- [x] reverse - closed by #4525
- [x] nushell/nushell#4444 
- [ ] nushell/nushell#4501
- [x] nushell/nushell#4503
- [x] make sure globs with external commands expand properly with PWD (https://github.com/nushell/engine-q/issues/835 and https://github.com/nushell/engine-q/issues/826)

**Comment by lukexor** [comment]
Is `autoenv` being postponed for release? If so it needs to get added to the breaking changes list. It's a critical feature for my every day work and I'd assume for others as well even for those who don't use python. I have several node and java projects with varying versions that I jump between.

**Comment by kubouch** [comment]
@lukexor Yes, we're leaving autoenv out for the 0.60 release and will re-introduce it later. BTW, what is your use case for autoenv? Do you use it to define environment variables only? Or do you define also custom commands?

**Comment by lukexor** [comment]
@kubouch Primarily modifying PATH and env vars like JAVA_HOME. Custom commands aren't a concern and have alternative work arounds. At present my only work around is a custom `cd` command or manually sourcing a nu file

**Comment by hustcer** [comment]
What's the status of `match`  command ?

**Comment by fdncred** [comment]
> What's the status of `match` command ?

we're looking for someone to port it and integrate that functionality into find. are you interested?

**Comment by hustcer** [comment]
@fdncred I'm interested in this, but I'm not familiar with Rust and if I were to develop it, it might take longer than expected. BTW, I don't know much about the overall architecture of the new engine. Is there a developer guide for the new engine?

**Comment by fdncred** [comment]
I don't want you to get overloaded. it would be nice to finish the examples first, if you don't mind. If you're not interested in finishing the examples, that's ok too. just let me know.

**Comment by hustcer** [comment]
@fdncred Sure, I will add examples for `n/p/g/grid`. 
The others: `export, extern, run-external`  I'm not quite familiar with the last two, and `export` is too important, It's better to have a more experienced person to handle

**Comment by jaeheonji** [comment]
List of missing `metadata` in `filter` commands.
(The following commands are missing `LS_COLORS`)

| Command                | Status  |
|------------------------|---------|
| `drop`                 | missing |
| `keep`                 | missing |
| `append`               | missing |
| `collect`              | missing |
| `compact`              | missing |
| `each` (group, window) | missing |
| `every`                | missing |
| `flatten`              | missing |
| `get`                  | missing |
| `headers`              | missing |
| `par-each` (group)     | missing |
| `prepend`              | missing |
| `range`                | missing |
| `reduce`               | missing |
| `reject`               | missing |
| `rename`               | missing |
| `rotate`               | missing |
| `select`               | missing |
| `shuffle`              | missing |
| `transpose`            | missing |
| `uniq`                 | missing |
| `update` (cell)        | missing |

Please let me know if I'm missing anything.

**Comment by fdncred** [comment]
@jaeheonji would you mind moving the missing metadata/ls_colors items above to a separate issue for better visibility and tracking?

**Comment by jaeheonji** [comment]
@fdncred Yes, of course! So, should I delete the above comment? Or should I leave it as is?

**Comment by fdncred** [comment]
@jaeheonji i'll delete it when the other issue is up. thank you for helping us!

**Comment by jaeheonji** [comment]
@fdncred Cool! thank you 😄  I'll try to create an issue ASAP.

**Comment by devurandom** [comment]
0.60 has long been released. Can this issue be closed?

**Comment by fdncred** [comment]
ya, we should probably close it. there are things still not ported but apparently no one really needs that funcitonality.
