### ISSUE TITLE
Engine-q final merge checklist

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#4357]
(warning: this list may not be complete, and may have items added as we discover them):

## Commands

- [x] get (remaining: ...rest)
- [x] group-by - [andres]
- [x] merge [Jakub]
- [x] move [Jakub]
- [x] save [jt]
- [x] sort-by - [storm]
- [x] str (conversion now in `into string`)
- [x] update cells
- [x] each window/each group - [jt]
- [x] pivot - [jt]
- [x] rename
- [x] split-by - [andres]
- [x] find - [arthur-targaryen]
- [ ] post - [efx]
- [x] which
- [x] seq
- [x] seq date - [darren]
- [x] term size - [darren]
- [ ] benchmark (remaining: passthrough param)
- [x] ls (remaining: --du flag) - [darren]
- [x] default - [jt]
- [x] hash (remaining: rest param) (JT: this appears to be a bug in the original nushell, `hash` just returns help)
- [x] hash base64 - [darren]
- [x] load-env
- [x] detect columns
- [x] du - [darren]
- [ ] match (regex type) (Jakub: I'd suggest folding it into `find`)
- [ ] roll
- [x] rotate
- [x] selector - [darren] to be `query web`
- [ ] headers
- [x] nu plugin (replaced by "register"? JT: I think this was original part of the testing infra and not intended for easy use by users. `register` should be a decent replacement for now)
- [x] tutor - [jt]
- [x] zip
- [x] exec - [jt]
- [ ] format filesize
- [x] query json - [darren] to be `query json`
- [ ] chart
- [ ] histogram
- [ ] reduce (parser support for `$acc` and `$it` instead of putting both inside `$it`)
- [x] xpath - [darren] to be `query xml`
- [x] error make - [jt]

## Features

- [x] completions for binaries in the PATH/Path
- [x] completions for variables
- [ ] completions for cell paths(?)
- [ ] finish custom external completions, `git` as main use case for initial design
- [x] keybindings file
- [x] can't run .cmd files in path (https://github.com/nushell/engine-q/issues/820)
- [x] external -> external should be seamless (https://github.com/nushell/engine-q/issues/819)
- [x] syntax highlight help examples - [jt]
- [ ] generate a config.nu if it's not there nushell/nushell#4348
- [x] `cd -` (https://github.com/nushell/engine-q/issues/577)
- [x] `help -f` to search help
- [x] commandline flags to nu (should come before the script filename, so they don't conflict with passing args to the script)
- [ ] lib_dirs (path for scripts, so `use` will look in these dirs)
- [x] CMD_DURATION_MS to get the execution time of the last command
- [ ] LAST_EXIT_CODE to get the exit code of the last command (internal or external)
- [x] Allow PROMPT_COMMAND to be a string
- [x] move every crate to edition 2021?
- [x] doc comments for custom commands (#809)
- [x] nu-test-support
- [x] nu script parameters and flags are buggy https://github.com/nushell/engine-q/issues/689
- [x] nushell/engine-q#514
- [x] `=` between flag and value

## Missing config points - to add or not to add?
- [ ] complete_from_path: bool
- [ ] ctrlc_exit: bool
- [ ] disable table indexes: bool
- [ ] nonzero_exit_errors: bool
- [x] plugin_dirs: list - not needed because register documents where plugins are at
- [ ] rm_always_trash: bool
- [ ] skip_welcome_message: bool
- [ ] pivot_mode: auto, always, never

## 3rd Party Integrations

We should ensure these are working or pr changes to their repo.

- [x] [zoxide](https://github.com/ajeetdsouza/zoxide)
- [x] [starship](https://starship.rs) - works
- [ ] [starship script to PR](https://github.com/starship/starship/blob/master/src/init/starship.nu)
- [ ] [starship docs to PR](https://github.com/starship/starship/tree/master/docs#nushell)
- [x] python virtualenv
- [x] couchbase
- [x] [oh-my-posh](https://ohmyposh.dev/docs/windows) - works
- [ ] [oh-my-posh docs to PR](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/docs/docs/install-shells.mdx#nu--0320)

## Document as "needs design" post-merge

- [ ] Autoenv
- [x] history file vs. multiple sessions? should be taken care of by https://github.com/nushell/reedline/pull/299

## CI / Repo Root folders

- [ ] release ci - do we need any changes? wix, etc
- [ ] winget ci
- [ ] stale ci - keep or chunk?
- [x] nushell uses azure pipelines, e-q uses github workflows
- [x] nushell uses circle ci and quay
- [x] nushell uses forms for issue templates - keep/chunk?
- [x] not sure if .theia is used
- [x] not sure if debian is used
- [x] not sure if docker still works
- [ ] wasm
- [x] gitpod

## Bugs

- [x] possible race condition: https://github.com/nushell/engine-q/issues/726
- [x] entering a file shouldn't be allowed: https://github.com/nushell/engine-q/issues/730
- [ ] `use` + path autocomplete: nushell/nushell#4352
- [x] zombie plugins: https://github.com/nushell/engine-q/issues/708
- [x] `cd crates; ls ..` does not work: https://github.com/nushell/engine-q/issues/745
- [x] Default line breaks do not work as expected: https://github.com/nushell/engine-q/issues/575

## Checks 

- [ ] make sure LS_COLORS is retained when passing `ls` through all the filters commands (see https://github.com/nushell/engine-q/pull/824) (fixed sort-by, find, merge, others?) nushell/nushell#4309 nushell/nushell#4306
- [x] make sure globs with external commands expand properly with PWD (https://github.com/nushell/engine-q/issues/835 and https://github.com/nushell/engine-q/issues/826)
