### ISSUE TITLE
implementation special variables and background jobs?

### ISSUE THREAD

**Issue by Rogn4r** [nushell/nushell#4564]
### Related problem

nushell didn't have implementation Unix special variables like $! $# $? $- etc also nushell not implemented a background jobs?

### Describe the solution you'd like

in any shell you can use this vars this link to powershell first link https://www.tutorialspoint.com/powershell/powershell_special_variables.htm or bash https://www.mylinuxplace.com/bash-special-variables/
 links for jobs in powershell https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_jobs?view=powershell-7 and bash https://www.gnu.org/software/bash/manual/html_node/Job-Control-Basics.html

**Comment by jntrnr** [comment]
Nushell has its own built-in special variables. For things like getting the commandline arguments, in the recent Nushell in main, you can create a `main` custom command, and the arguments you define for that will become script parameters.

**Comment by Rogn4r** [comment]
plz explain how implement script like this in nushell
#!/bin/bash
echo "job for $1s" && sleep $1 &
PID=$!
echo "job for $2s" && sleep $2 &
wait $PID
echo "1st job exit status $?"
wait $!
echo "job2 exit status $?"

**Comment by hustcer** [comment]
$! and $? not supported currently?

**Comment by dscottboggs** [comment]
I came across this while wondering about job control, and thought I'd organize and clarify the issue. Each item can be marked implemented, not implemented, or ~~won't implement~~.

# Special variables
BASH and friends have [special variables](https://linuxconfig.org/special-bash-variables-with-examples) which are set each time a command is run.
- [x] `$?`: exit code of previous command. **`nu` equivalent**: `$env.LAST_EXIT_CODE`
- [ ] `$$`: shell's PID
- `$n`: arguments passed to nu.
   - [x] Nu: in nu scripts, define a `main` command which accepts some arguments.
   - [ ] NuShell
- [ ] `$0`: the command the shell was run with
- [ ] `$*` (or `zsh`'s `$@`): The complete list of arguments passed to the shell
- [ ] ~~`zsh`'s `$*`: a space separated list of strings passed to the shell~~; why?

# Job control
BASH and friends have the ability to pause a job, send it to the background, or resume it in the foreground. I don't know much about the architecture of nushell, but I can assume this would mean a major refactoring in order to use an async runtime to manage jobs. Still, I think it's worth considering as a long-term goal.

- [ ] respond to `^Z` (Ctrl+Z)
- [ ] equivalent of the `&` operator. I would assume the "nu" way of doing this would be to add a command like `some-command | background` or an option to `do` like `do --in-background { some-command }`
- [ ] `fg` command
- [ ] `bg` command
- [ ] `jobs` command

**Comment by computerquip** [comment]
So for the sake of scripting, does nushell not currently support asynchronous jobs at all?
For example, in bash, you could do something like:
```
pids=()

long_running_program &
pids+=($!)

another_long_running_program &
pids+=($!)

wait "$pids"
```

**Comment by dgengtek** [comment]
@Rogn4r

Something like this maybe, obviously not equivalent since bash is definitely superior in job control.
```
def run [i: int] {
  print $"job for ($i)s"
  sleep ($"($i)sec" | into duration)
  let randint = (random integer 1..100)
  print $"running some command which exits from ($i)"
  do {
    bash --noprofile --norc -c $"exit ($randint)"
  } | complete
}


def main [one: int, two: int] {
  [$one $two] | par-each { || run $in }
}
```



@computerquip, you can with par-each

`['ls test aa' 'ls /' 'echo -e test2\n newline' 'sleep 4' 'bash -c "notexist"'] | par-each {|i| let a = ($i | split row " "); do { ^($a | first) ($a | skip) } | complete }`

**Comment by jokeyrhyme** [comment]
They do document how to achieve background tasks here: https://www.nushell.sh/book/background_task.html
The main suggestion is to use `pueue`: https://github.com/Nukesor/pueue

**Comment by WindSoilder** [comment]
Job control already handled by #14883

**Comment by 132ikl** [comment]
There's a lot going on in this issue, and some things have been implemented and some haven't. I'm going to close this issue, and provide a corresponding implemented feature or issue for each sub-point raised in this issue. If I missed anything or you disagree with my assessment, comment your concern here and I can make a new issue, or feel free to make a new issue yourself.

As Wind says job control is implemented by #14883, and I've created a new meta issue for job control features which individually tracks the issues brought up in this thread. Specifically:

* respond to ^Z (Ctrl+Z): implemented by #14883. for external commands, see #15197 for internal commands
* equivalent of the & operator: `job spawn { command }`
* fg command: `job unfreeze` for suspended jobs, see #15202 for other jobs
* bg command: #15196 
* jobs command: `job list`
* wait command: #15198
* disown command: #15201, also related #15200

For the special variables, here's equivalents:

- `$?` -> `$env.LAST_EXIT_CODE`
- `$$`: shell's PID -> `$nu.pid`
- `$n`: arguments passed to nu.
   - In scripts: in nu scripts, define a `main` command which accepts some arguments.
   - In shell: this isn't really applicable, you can't pass arguments directly to the `bash` executable and have them accessible in the shell, and the same is true for Nushell.
- `$0`: We don't have a way to get `argv[0]` specifically, but there is `$nu.current-exe` and `$env.CURRENT_FILE`. If neither of these meet your needs, we can create a new issue for it.
- `$@` / `$*`: It's not exactly the same, but you can use [rest parameters](https://www.nushell.sh/book/custom_commands.html#rest-parameters) for this. Getting command arguments as strings isn't really useful in Nushell. If you have some use case that you can't meet with rest parameters, please make a new issue with your use case.
