### ISSUE TITLE
Status of equivalents of BASH history expansion

### ISSUE THREAD

**Issue by dscottboggs** [nushell/nushell#5011]
### Related problem

BASH and friends support [history expansion](https://manpage.me/?q=bash#HISTORY_EXPANSION). In v0.60.0, nushell added support for *some* history expansion. I thought it would be helpful to organize what behavior is and is not supported, and progress of implementation in an issue.

### Describe the solution you'd like

Implementation of the following expansions, or "nu"-style equivalents.

# Event designators
- [x] `!!`
- [x] `!n` where n is a row in the history, positive (from the beginning), or negative (from the end)
- [ ] `!string`: run the last command in history which begins with "string"
- [x] `!?string[?]`: run the last command in history containing "string". In nu: `^X` (Ctrl+X) to search history
- [ ] `!#`: ditto of what has already been typed.

# Word designators
select which word from the entry in history. This might seem contrived, but I have some strong muscle memory for `!$`, hence the 'feature request'.

- [ ] `!:0`: the first word of the previous line, i.e. the command
- [ ] `!:n`: the nth argument in the previous line
- [ ] `!:^`/`!^`: the first argument to the command
- [x] `!:$`/`!$`: the last word of the previous line
- ~~`!:%`/`!%`: the word matched by the last `?string?` search~~ this doesn't make a ton of sense _if_ we're considering the `^X` search to be the equivalent
- [ ] `!:*`/`!*`: the whole previous line except the command/first word
- [ ] `!:x-y`: word `x` to `y`, inclusive
- [ ] `!:x*`: word `x` to the last word, inclusive
- [ ] `!:x-`: word `x` to the last word, exclusive

# Modifiers
> After the optional word designator, there may appear a sequence of one or more of the following modifiers, each preceded by a `:'.
- [ ] `h`: head
- [ ] `t`: tail
- [ ] `r`: remove filename extension
- [ ] `e`: extract the filename extension only
- [x] `p`: print the new command, but do not execute (`!!` commands as implemented now are displayed on enter, not executed. This seems smarter anyway).
- [ ] `q`: Quote the substituted words, escaping further substitutions. (what?)
- [ ] `x`: like q, but splits into words on whitespace?
- [ ] `s/old/new`: substitution
- [ ] `&`: repeat the substitution
- [ ] `g`: Cause changes to be applied over the entire event line, (as opposed to the first found instance)
- [ ] `G`: apply to each word

### Additional context and details

I'm really just looking for `!$` here, but I thought it might be useful to write the rest of them down too.

This kind-of relates to #4564

**Comment by fdncred** [comment]
thanks for taking the time to put this together. yes, I'm missing `!$` too.

**Comment by dscottboggs** [comment]
0.61 just dropped, and now `!$` works! What PR was that added in?

**Comment by fdncred** [comment]
I think it's these.
https://github.com/nushell/nushell/pull/5062
https://github.com/nushell/reedline/pull/374

I'm not sure if any more of these will be added.

**Comment by jntrnr** [comment]
This looks likely the limit we'll get too. We'd like Nushell to be comfortable coming from other shells, but we're unlikely to add the same set of magic variables bash provides. Thanks again.
