### ISSUE TITLE
Nushell 0.70 - Release checklist

### ISSUE THREAD

**Issue by sholderbach** [nushell/nushell#6636]
Nushell **0.70.0** is slated to be released on **2022-10-18**

### T - ? days
- [x] checked the state of other dependencies
  - [x] `crossterm`
  - [x] `nu-ansi-term`
  - [x] `tabled`
  - [ ] ... 
### T - 1 day
- [x] [`reedline`](https://github.com/nushell/reedline) is released on [crates.io](https://crates.io/crates/reedline) and the release notes are tagged on Github
- [x] Blog post is ready (add your breaking changes to the [release-notes-0.70](https://github.com/nushell/nushell.github.io/tree/release-notes-0.70) branch)
- [ ] New features and changes are properly going into the written documentation
- [x] Version bump PR ready to go (upgrading to `0.minor.0` version ) 
### Release day
- [x] press the release nu button (Q: maybe include `cargo publish --dry-run` in the release script to check dependency tree problems)
- [x] publish blogpost and land docs PRs for new features
- [x] Social media
- [x] patch version bump to identify post launch changes
