### ISSUE TITLE
Release checklist 0.72

### ISSUE THREAD

**Issue by sholderbach** [nushell/nushell#6849]
Nushell **0.72.0** is slated to be released on **2022-11-29**

### T - ? days
- [ ] checked the state of other dependencies
  - [ ] `crossterm` (goal for `0.72`, `crossterm 0.25` upgrade on the `reedline` side)
  - [ ] `nu-ansi-term`
  - [ ] `tabled`
  - [ ] ... 
### T - 1 day
- [ ] [`reedline`](https://github.com/nushell/reedline) is released on [crates.io](https://crates.io/crates/reedline) and the release notes are tagged on Github
- [ ] Blog post is ready (add your breaking changes to the respective release note branch [release-notes-0.72](https://github.com/nushell/nushell.github.io/pull/666))
- [ ] New features and changes are properly going into the [written documentation](https://github.com/nushell/nushell.github.io).
- [ ] Version bump PR ready to go (upgrading to `0.minor.0` version ) 
### Release day
- [ ] press the release nu button (Q: maybe include `cargo publish --dry-run` in the release script to check dependency tree problems)
- [ ] publish blogpost and land docs PRs for new features
- [ ] Social media
### Immediately following release
- [ ] patch version bump to identify post launch changes
- [ ] Run command documentation workflow (@hustcer)
