### ISSUE TITLE
Missing type information for builtins to be filled out

### ISSUE THREAD

**Issue by sholderbach** [nushell/nushell#7320]
Since #6796 commands can declare the types they take as pipeline input and return as pipeline output.

To do so they declare the pairs of input and output type via [`Signature.input_output_types()`](https://docs.rs/nu-protocol/latest/nu_protocol/struct.Signature.html#method.input_output_types).
If the command both operates on a singular scalar value and a list of values this can be expressed with [`Signature.vectorizes_over_list(true)`](https://docs.rs/nu-protocol/latest/nu_protocol/struct.Signature.html#method.vectorizes_over_list).
Similarly commands that can optionally work on specific columns/fields of a table or nested datastructure can say that they take a cell path with [`Signature.operates_on_cell_paths()`](https://docs.rs/nu-protocol/latest/nu_protocol/struct.Signature.html#method.operates_on_cell_paths)
Those types can be directly tested through the `Command.examples()`. If you can not declare a good runnable example you can [turn off exhaustive checking](https://docs.rs/nu-protocol/latest/nu_protocol/struct.Signature.html#method.allow_variants_without_examples) as an escape hatch.

Being more thorough there will allow us to provide better error messages and helpful documentation for the users.

A related issue caused by missing type info  is #7287

## Example 

https://github.com/nushell/nushell/blob/b650d1ef7963df3a57c89d0ae849ec8ad7b1d5a3/crates/nu-command/src/conversions/into/filesize.rs#L13-L31

## List of commands:
- [x] `ansi gradient`
- [x] `benchmark`
- [x] `bits`
- [x] `bytes`
- [x] `cd`
- [x] `clear`
- [x] `complete`
- [x] `config`
- [x] `config env` (slightly cheating)
- [x] `config nu` (slightly cheating)
- [x] `config reset`
- [x] `cp`
- [x] `date`
- [x] `du`
- [x] `enter`
- [x] `env`
- [x] `error make`
- [x] `exec` (slightly cheating)
- [x] `exit`
- [x] `explore`
- [x] `fetch`
- [x] `for`
- [x] `from`
- [x] `from yml`
- [x] `g`
- [x] `glob`
- [x] `hash`
- [ ] `hash base64` (deprecated command)
- [x] `help operators`
- [x] `history`
- [x] `history session`
- [x] `input`
- [x] `into`
- [x] `into sqlite`
- [x] `is-admin` (may need different example)
- [x] `keybindings`
- [x] `keybindings default`
- [x] `keybindings list`
- [x] `keybindings listen`
- [x] `kill`
- [x] `let-env`
- [x] `load-env`
- [x] `loop`
- [x] `ls`
- [x] `math`
- [x] `mkdir`
- [x] `mv`
- [x] `n`
- [x] `nu-check`
- [x] `nu-highlight`
- [x] `open`
- [x] `overlay`
- [x] `overlay hide`
- [x] `overlay list`
- [x] `overlay new`
- [x] `overlay use`
- [x] `p`
- [x] `path`
- [x] `port`
- [x] `post`
- [x] `print`
- [x] `ps`
- [x] `query db`
- [x] `random`
- [x] `random bool`
- [x] `random chars`
- [x] `random decimal`
- [x] `random dice`
- [x] `random integer`
- [x] `random uuid`
- [x] `rm`
- [x] `roll`
- [x] `run-external`
- [x] `save`
- [x] `schema`
- [x] `shells`
- [x] `source`
- [x] `source-env`
- [x] `split`
- [x] `str`
- [ ] `str find-replace` (deprecated)
- [ ] `str to-datetime` (deprecated)
- [ ] `str to-decimal` (deprecated)
- [ ] `str to-int` (deprecated)
- [x] `sys`
- [x] `table` (narrowing the type to steaming vs value would be helpful)
- [x] `term size`
- [x] `to`
- [x] `touch`
- [x] `tutor`
- [x] `view-source`
- [x] `watch`
- [x] `which`
- [x] `while`

**Comment by sholderbach** [comment]
I think it is helpful to know that for example `for` now doesn't return anything.
We could even go further and introduce a new type "don't pipe me" like rusts `!` that will always error.

**Comment by fdncred** [comment]
I'm trying to make sense of all these signature parameters. Please correct me if this is wrong because I'm not sure about some of these.

1. Use `allow_variants_without_examples(true)` if the `fn examples()` can *only* but `None`.
2. Use `operates_on_cell_paths(true)` if the command has a `rest` parameter with the shape of `SyntaxShape::CellPath`.
3. Use `vectorizes_over_lists(true)` if the command uses the `operate` function that allows tables to be piped into the command.
4. List of all possible Input/Output Types and how to specify them in the signature:
- Type::Any
- Type::Binary
- Type::Block
- Type::Bool
- Type::CellPath
- Type::Closure
- Type::Custom("some string") <-- there's some of these in the dataframes since it returns a custom value
- Type::Date
- Type::Duration
- Type::Error
- Type::Filesize
- Type::Float
- Type::Int
- Type::List(Box::new(Type::Any)) <-- maybe not always type any?
- Type::ListStream
- Type::Nothing
- Type::Number <-- really don't understand when to use number vs float vs int
- Type::Range
- Type::Record(vec![])
- Type::Signature
- Type::String
- Type::Table(vec![])

**Comment by hustcer** [comment]
I have carefully checked every commands list above and find that some of them needn't be fixed. So we just need to fix about 50 commands 🤣

**Comment by fdncred** [comment]
@hustcer I think you're right on some of these like the deprecated commands but I'm not sure about some of these like `env` has a table as output. `help operators` outputs a table. the base commands like `date`, `bits`, `bytes` output a string. 

Shouldn't we still describe the output even if there are no parameters?

**Comment by sholderbach** [comment]
Although our first priority is to finally ship the commnand docs, I think the boxes here should only be checked if we have the type info we want. 

So by all means land those docs, but keep the type specification open. (We have two issues for it already, and the intent for this one was to track the type system work)

**Comment by fdncred** [comment]
@hustcer maybe as a compromise, you could uncheck the ones that don't have type information added that still need them and modify the ones that are needed by docs like `- [ ] while - needed by docs`? This way we can focus on getting the ones completed first that are needed to make doc generation work, and then come back in a second pass and fix the rest of them.

**Comment by sholderbach** [comment]
All commands except the deprecated ones should now have a input output type as soon as #7532 lands

**Comment by hustcer** [comment]
Just find some other commands that might missing type information on the latest main:
```
> $nu.scope.commands | where is_builtin | where {|c| ($c.signatures | is-empty) == true } | where category != 'deprecated' | select name signatures category

   #        name            signatures              category
────────────────────────────────────────────────────────────────────
   0   agg               {record 0 fields}   lazyframe
   1   agg-groups        {record 0 fields}   expression
   2   all-false         {record 0 fields}   dataframe
   3   all-true          {record 0 fields}   dataframe
   4   append            {record 0 fields}   dataframe
   5   arg-max           {record 0 fields}   dataframe
   6   arg-min           {record 0 fields}   dataframe
   7   arg-sort          {record 0 fields}   dataframe
   8   arg-true          {record 0 fields}   dataframe
   9   arg-unique        {record 0 fields}   dataframe
  10   arg-where         {record 0 fields}   expression
  11   as                {record 0 fields}   expression
  12   as-date           {record 0 fields}   dataframe
  13   as-datetime       {record 0 fields}   dataframe
  14   cache             {record 0 fields}   lazyframe
  15   col               {record 0 fields}   expression
  16   collect           {record 0 fields}   lazyframe
  17   columns           {record 0 fields}   dataframe
  18   concat-str        {record 0 fields}   expression
  19   concatenate       {record 0 fields}   dataframe
  20   contains          {record 0 fields}   dataframe
  21   count             {record 0 fields}   expression
  22   count-null        {record 0 fields}   dataframe
  23   cumulative        {record 0 fields}   dataframe
  24   df-not            {record 0 fields}   dataframe
  25   drop              {record 0 fields}   dataframe
  26   drop-duplicates   {record 0 fields}   dataframe
  27   drop-nulls        {record 0 fields}   dataframe
  28   dtypes            {record 0 fields}   dataframe
  29   dummies           {record 0 fields}   dataframe
  30   explode           {record 0 fields}   expression
  31   expr-not          {record 0 fields}   expression
  32   fetch             {record 0 fields}   lazyframe
  33   fill-nan          {record 0 fields}   lazyframe
  34   fill-null         {record 0 fields}   lazyframe
  35   filter            {record 0 fields}   lazyframe
  36   filter-with       {record 0 fields}   dataframe or lazyframe
  37   first             {record 0 fields}   expression
  38   first             {record 0 fields}   dataframe
  39   flatten           {record 0 fields}   expression
  40   get               {record 0 fields}   dataframe
  41   get-day           {record 0 fields}   dataframe
  42   get-hour          {record 0 fields}   dataframe
  43   get-minute        {record 0 fields}   dataframe
  44   get-month         {record 0 fields}   dataframe
  45   get-nanosecond    {record 0 fields}   dataframe
  46   get-ordinal       {record 0 fields}   dataframe
  47   get-second        {record 0 fields}   dataframe
  48   get-week          {record 0 fields}   dataframe
  49   get-weekday       {record 0 fields}   dataframe
  50   get-year          {record 0 fields}   dataframe
  51   group-by          {record 0 fields}   lazyframe
  52   gstat             {record 0 fields}   prompt
  53   inc               {record 0 fields}   default
  54   into df           {record 0 fields}   dataframe
  55   into lazy         {record 0 fields}   lazyframe
  56   into nu           {record 0 fields}   expression
  57   into nu           {record 0 fields}   dataframe
  58   is-duplicated     {record 0 fields}   dataframe
  59   is-in             {record 0 fields}   dataframe
  60   is-in             {record 0 fields}   expression
  61   is-not-null       {record 0 fields}   dataframe
  62   is-not-null       {record 0 fields}   expression
  63   is-null           {record 0 fields}   expression
  64   is-null           {record 0 fields}   dataframe
  65   is-unique         {record 0 fields}   dataframe
  66   join              {record 0 fields}   lazyframe
  67   last              {record 0 fields}   expression
  68   last              {record 0 fields}   dataframe
  69   list              {record 0 fields}   expression
  70   lit               {record 0 fields}   expression
  71   lowercase         {record 0 fields}   dataframe
  72   ls-df             {record 0 fields}   dataframe
  73   max               {record 0 fields}   expression
  74   max               {record 0 fields}   lazyframe
  75   mean              {record 0 fields}   expression
  76   mean              {record 0 fields}   lazyframe
  77   median            {record 0 fields}   lazyframe
  78   median            {record 0 fields}   expression
  79   melt              {record 0 fields}   dataframe
  80   min               {record 0 fields}   expression
  81   min               {record 0 fields}   lazyframe
  82   n-unique          {record 0 fields}   dataframe
  83   n-unique          {record 0 fields}   expression
  84   open-df           {record 0 fields}   dataframe
  85   otherwise         {record 0 fields}   expression
  86   quantile          {record 0 fields}   expression
  87   quantile          {record 0 fields}   lazyframe
  88   query             {record 0 fields}   filters
  89   query df          {record 0 fields}   dataframe
  90   query json        {record 0 fields}   filters
  91   query web         {record 0 fields}   network
  92   query xml         {record 0 fields}   filters
  93   rename            {record 0 fields}   dataframe or lazyframe
  94   replace           {record 0 fields}   dataframe
  95   replace-all       {record 0 fields}   dataframe
  96   reverse           {record 0 fields}   lazyframe
  97   rolling           {record 0 fields}   dataframe
  98   sample            {record 0 fields}   dataframe
  99   select            {record 0 fields}   lazyframe
 100   set               {record 0 fields}   dataframe
 101   set-with-idx      {record 0 fields}   dataframe
 102   shape             {record 0 fields}   dataframe
 103   shift             {record 0 fields}   dataframe or lazyframe
 104   slice             {record 0 fields}   dataframe
 105   sort-by           {record 0 fields}   lazyframe
 106   std               {record 0 fields}   expression
 107   std               {record 0 fields}   lazyframe
 108   str-lengths       {record 0 fields}   dataframe
 109   str-slice         {record 0 fields}   dataframe
 110   strftime          {record 0 fields}   dataframe
 111   sum               {record 0 fields}   expression
 112   sum               {record 0 fields}   lazyframe
 113   summary           {record 0 fields}   dataframe
 114   take              {record 0 fields}   dataframe
 115   to arrow          {record 0 fields}   dataframe
 116   to csv            {record 0 fields}   dataframe
 117   to parquet        {record 0 fields}   dataframe
 118   unique            {record 0 fields}   dataframe or lazyframe
 119   uppercase         {record 0 fields}   dataframe
 120   value-counts      {record 0 fields}   dataframe
 121   var               {record 0 fields}   expression
 122   var               {record 0 fields}   lazyframe
 123   when              {record 0 fields}   expression
 124   with-column       {record 0 fields}   dataframe or lazyframe
────────────────────────────────────────────────────────────────────
   #        name            signatures              category
```
