### ISSUE TITLE
standard library: a roadmap

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8450]
### Describe the solution you'd like

- [ ] distribution of `std.nu`
- [ ] `CONTRIBUTING.md`
- [ ] populating with command ideas, from the `rust` source base or from `nu_scripts`
  - #8311
- [ ] bring the tests to the main CI
- [ ] structuring the architecture of the library
  - [`amtoine/test-nu-std`](https://github.com/amtoine/test-nu-std)
- [ ] versioning system to tie the library to a `nushell` revision and avoid conflicts
  - [#standard-library/stdlib versioning](https://discord.com/channels/601130461678272522/1084848798385307719)

> **Note**
> see
> - the [opened issues](https://github.com/nushell/nushell/issues?q=is%3Aissue+is%3Aopen+label%3Astd-library+)
> - the [opened PRs](https://github.com/nushell/nushell/pulls?q=is%3Apr+is%3Aopen+label%3Astd-library)
> - and all of them [here](https://github.com/nushell/nushell/labels/std-library)

**Comment by amtoine** [comment]
## :warning: important issues to address
- [ ] #8528

**Comment by amtoine** [comment]
i started working on removing the `help` commands from the `rust` source, but it's a bit more work than expected :thinking: 

i'll continue in the following days!

it remind me of the need to have some kind of "prelude" as been said during the #open-mic yesterday

- load important commands from the standard library, e.g. the `help` familly, from a "prelude"
