### ISSUE TITLE
Wishlist for 0.5.0 (and soon after)

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#900]
- [ ] ~Using $it on a whole-stream command~
- [x] Allow for setting config variables from the pipeline
- [x] Echo that can echo any value, not just strings
- [x] Better internal->external support (we currently don't have any support to stream into the external command stdin)
- [x] Environment variable support (similar to how we have $nu:path now)
- [x] Plugins should respect $nu:path (they currently don't, which makes it hard to use Nu as a login shell)
- [x] "tiling the space" doc. Document all the current functionality for navigating, filtering, and updating tables. Document the gaps for possible future commands
- [x] Row numbers in paths
- [x] Differentiate between numbers in path and number-in-string paths
- [x] Rename `add` to `insert`
- [ ] Explore what virtualenv needs
- [x] Move `fetch` to a plugin so that the Nu binary doesn't link directly to openssl
- [x] Add starship prompt support
- [x] Trim `ls` down a bit, and add a new `--full` flag to `ls` that gives even more columns. This should help with 80x24 use of Nu
- [x] Fix printing of mixed-value tables
- [x] Filter on the existence of a field. (#800)
- [ ] Configure how values are serialized from internal commands to external ones. (#778)
- [x] Broader support when piping internal commands to external ones. (#412)
- [ ] Signing binary releases. (#754)
- [x] Extend `nth` to take multiple arguments. (#878)
- [x] Report error when `pick` tries columns that doen't exist. (#750)
- [ ] Support command based completions. (#749)
- [ ] Support setting colors scheme from `config` (#747) 
- [ ] Debian packaging. (#741)
- [ ] Support '&&' equivalent for separating multiple commands. (#740)

**Comment by jonathandturner** [comment]
Just going to close this as I'm not sure it's helpful anymore.
